services:
  postgres:
    image: postgres:15-alpine
    container_name: minesweeper-db
    environment:
      POSTGRES_DB: minesweeper_db
      POSTGRES_USER: minesweeper_user
      POSTGRES_PASSWORD: minesweeper_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U minesweeper_user -d minesweeper_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: minesweeper-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://minesweeper_user:minesweeper_password@postgres:5432/minesweeper_db?schema=public"
      PORT: 3001
      NODE_ENV: development
      FRONTEND_URL: http://localhost:3000
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: minesweeper-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
